#!/bin/sh

# Set these paths appropriately

BIN=/auto_home/hdossantosma/Documents/m1/s2/fouillededonnees/git/review-classification/treetagger/bin
CMD=/auto_home/hdossantosma/Documents/m1/s2/fouillededonnees/git/review-classification/treetagger/cmd
LIB=/auto_home/hdossantosma/Documents/m1/s2/fouillededonnees/git/review-classification/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian-utf8.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
