#!/bin/sh

# Set these paths appropriately

BIN=/auto_home/hdossantosma/Documents/m1/s2/fouillededonnees/git/review-classification/treetagger/bin
CMD=/auto_home/hdossantosma/Documents/m1/s2/fouillededonnees/git/review-classification/treetagger/cmd
LIB=/auto_home/hdossantosma/Documents/m1/s2/fouillededonnees/git/review-classification/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/latin-abbreviations
PARFILE=${LIB}/latin.par
MWLFILE=${LIB}/latin-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

